### PR TITLE
Simplify connection handling

### LINKED ISSUE #67: Disconnect broken
Refs https://github.com/evcc-io/evcc/issues/17446#issuecomment-2508086667

In

```go
// Disconnect the client
func (c *Client) Disconnect() error {
	c.isAuthenticated = false
	c.isConnected = false

        // -> THIS BLOCK CAN NEVER EXECUTE
	if c.isConnected && c.conn != nil {
		if err := c.conn.Close(); err != nil {
			return err
		}
	}

	Log.Info("disconnected")
	return nil
}
```

### PR DESCRIPTION
**Pull request by andig**
Fix https://github.com/spali/go-rscp/issues/67

### CODE REVIEW

File: rscp/client.go [hunk 1]
```diff
@@ -105,17 +102,15 @@ func (c *Client) receive() ([]Message, error) {
...
+
+	conn, err := net.DialTimeout("tcp", c.connectionString, c.config.ConnectionTimeout)
+	if err != nil {
 		return err
 	}
-	c.conn = conn
-	c.isConnected = true
+
 	Log.Infof("successfully connected to %s", c.conn.RemoteAddr())
+	c.conn = conn
```
Comment (spali) [inline rscp/client.go:112]: Needs to be above line 111, as `c.conn` is accessed when `nil`.

Comment (spali) [reply rscp/client.go:112]: Tested with the the above mentioned change and at least the command line utility does work as I expect it.
Would be nice if you could squash the commits into one, so I could do a single commit rebase. Otherwise I would do a squash merge.

Comment (andig) [reply rscp/client.go:112]: Thanks, fixed. Would be great if you could squash on merge.

**Comment by spali** [comment]
@andig Thanks for the contribution

**Comment by andig** [comment]
You‘re welcome, thanks for the module!
